services:
  file_log_service:
    image: local-dev:0.1
    ports: 
      - "$LOCAL_HOST_PORT:8100"
    volumes:
      - $LOCAL_DEV_STORAGE_DIR:/usr/storagedir
      - $LOCAL_DEV_LOG_DIR:/usr/logdir
  
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      # test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 1